### ISSUE TITLE
When I tested it, it gives an importerror: no module named _crop_and_resize

### ISSUE THREAD

**Issue by chang0977** [longcw/RoIAlign.pytorch#12]
sudo python tests/test.py

('Unexpected error:', <type 'exceptions.ImportError'>)
Traceback (most recent call last):
  File "tests/test.py", line 13, in <module>
    from roi_align.crop_and_resize import CropAndResizeFunction
  File "/usr/local/lib/python2.7/dist-packages/roi_align-0.0.1-py2.7.egg/roi_align/crop_and_resize.py", line 7, in <module>
    from ._ext import crop_and_resize as _backend
  File "/usr/local/lib/python2.7/dist-packages/roi_align-0.0.1-py2.7.egg/roi_align/_ext/crop_and_resize/__init__.py", line 3, in <module>
    from ._crop_and_resize import lib as _lib, ffi as _ffi
ImportError: No module named _crop_and_resize

**Comment by gjd2017** [comment]
I also have this problem, Do you have solved it?

**Comment by gjd2017** [comment]
Thanks , got it.

**Comment by holyYodu** [comment]
python setup.py install
running install
running bdist_egg
running egg_info
creating roi_align.egg-info
writing roi_align.egg-info\PKG-INFO
writing dependency_links to roi_align.egg-info\dependency_links.txt
writing requirements to roi_align.egg-info\requires.txt
writing top-level names to roi_align.egg-info\top_level.txt
writing manifest file 'roi_align.egg-info\SOURCES.txt'
reading manifest file 'roi_align.egg-info\SOURCES.txt'
writing manifest file 'roi_align.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.6
creating build\lib.win-amd64-3.6\roi_align
copying roi_align\crop_and_resize.py -> build\lib.win-amd64-3.6\roi_align
copying roi_align\roi_align.py -> build\lib.win-amd64-3.6\roi_align
copying roi_align\__init__.py -> build\lib.win-amd64-3.6\roi_align
running build_ext
error: [WinError 2] 系统找不到指定的文件。


when i compile roi_align , this error occured. what should i do to solve this problem? or are there any packages that i didn't install ?

**Comment by yyc-0126** [comment]
> python setup.py install
> running install
> running bdist_egg
> running egg_info
> creating roi_align.egg-info
> writing roi_align.egg-info\PKG-INFO
> writing dependency_links to roi_align.egg-info\dependency_links.txt
> writing requirements to roi_align.egg-info\requires.txt
> writing top-level names to roi_align.egg-info\top_level.txt
> writing manifest file 'roi_align.egg-info\SOURCES.txt'
> reading manifest file 'roi_align.egg-info\SOURCES.txt'
> writing manifest file 'roi_align.egg-info\SOURCES.txt'
> installing library code to build\bdist.win-amd64\egg
> running install_lib
> running build_py
> creating build
> creating build\lib.win-amd64-3.6
> creating build\lib.win-amd64-3.6\roi_align
> copying roi_align\crop_and_resize.py -> build\lib.win-amd64-3.6\roi_align
> copying roi_align\roi_align.py -> build\lib.win-amd64-3.6\roi_align
> copying roi_align__init__.py -> build\lib.win-amd64-3.6\roi_align
> running build_ext
> error: [WinError 2] 系统找不到指定的文件。
> 
> when i compile roi_align , this error occured. what should i do to solve this problem? or are there any packages that i didn't install ?

same question
