### ISSUE TITLE
pytorch-1.0

### ISSUE THREAD

**Issue by fabienbaradel** [longcw/RoIAlign.pytorch#20]
Hi,
I cannot install your RoIAlign with the latest pytorch version (stable 1.0). I get the following error when I run the `install.sh`:
```
Compiling crop_and_resize kernels by nvcc...
./install.sh: ligne 7: /usr/local/cuda/bin/nvcc: Aucun fichier ou dossier de ce type
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/home/fbaradel/anaconda3/envs/pytorch-1.0/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
running install
running bdist_egg
running egg_info
creating roi_align.egg-info
writing roi_align.egg-info/PKG-INFO
writing dependency_links to roi_align.egg-info/dependency_links.txt
writing requirements to roi_align.egg-info/requires.txt
writing top-level names to roi_align.egg-info/top_level.txt
writing manifest file 'roi_align.egg-info/SOURCES.txt'
reading manifest file 'roi_align.egg-info/SOURCES.txt'
writing manifest file 'roi_align.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/roi_align
copying roi_align/build.py -> build/lib/roi_align
copying roi_align/crop_and_resize.py -> build/lib/roi_align
copying roi_align/roi_align.py -> build/lib/roi_align
copying roi_align/__init__.py -> build/lib/roi_align
creating build/lib/roi_align/_ext
copying roi_align/_ext/__init__.py -> build/lib/roi_align/_ext
creating build/lib/roi_align/_ext/crop_and_resize
copying roi_align/_ext/crop_and_resize/__init__.py -> build/lib/roi_align/_ext/crop_and_resize
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/roi_align
copying build/lib/roi_align/build.py -> build/bdist.linux-x86_64/egg/roi_align
copying build/lib/roi_align/crop_and_resize.py -> build/bdist.linux-x86_64/egg/roi_align
creating build/bdist.linux-x86_64/egg/roi_align/_ext
creating build/bdist.linux-x86_64/egg/roi_align/_ext/crop_and_resize
copying build/lib/roi_align/_ext/crop_and_resize/__init__.py -> build/bdist.linux-x86_64/egg/roi_align/_ext/crop_and_resize
copying build/lib/roi_align/_ext/__init__.py -> build/bdist.linux-x86_64/egg/roi_align/_ext
copying build/lib/roi_align/roi_align.py -> build/bdist.linux-x86_64/egg/roi_align
copying build/lib/roi_align/__init__.py -> build/bdist.linux-x86_64/egg/roi_align
byte-compiling build/bdist.linux-x86_64/egg/roi_align/build.py to build.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/roi_align/crop_and_resize.py to crop_and_resize.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/roi_align/_ext/crop_and_resize/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/roi_align/_ext/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/roi_align/roi_align.py to roi_align.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/roi_align/__init__.py to __init__.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying roi_align.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying roi_align.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying roi_align.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying roi_align.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying roi_align.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
roi_align.__pycache__.build.cpython-36: module references __file__
creating dist
creating 'dist/roi_align-0.0.1-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing roi_align-0.0.1-py3.6.egg
creating /home/fbaradel/anaconda3/envs/pytorch-1.0/lib/python3.6/site-packages/roi_align-0.0.1-py3.6.egg
Extracting roi_align-0.0.1-py3.6.egg to /home/fbaradel/anaconda3/envs/pytorch-1.0/lib/python3.6/site-packages
Adding roi-align 0.0.1 to easy-install.pth file

Installed /home/fbaradel/anaconda3/envs/pytorch-1.0/lib/python3.6/site-packages/roi_align-0.0.1-py3.6.egg
Processing dependencies for roi-align==0.0.1
Searching for cffi==1.11.5
Best match: cffi 1.11.5
Adding cffi 1.11.5 to easy-install.pth file

Using /home/fbaradel/anaconda3/envs/pytorch-1.0/lib/python3.6/site-packages
Searching for pycparser==2.19
Best match: pycparser 2.19
Adding pycparser 2.19 to easy-install.pth file

Using /home/fbaradel/anaconda3/envs/pytorch-1.0/lib/python3.6/site-packages
Finished processing dependencies for roi-align==0.0.1
```
It seems that the `create_extension` has moved somewhere else...
Thanks for your answer.

**Comment by longcw** [comment]
This repo only supports pytorch < 0.4. You can find a new version from [facebookresearch/maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark/tree/master/maskrcnn_benchmark/csrc).

**Comment by fabienbaradel** [comment]
Ok

**Comment by IssamLaradji** [comment]
I didn't find the `crop_and_resize` function there.
