### ISSUE TITLE
pytorch1.0 ffi was deprecated

### ISSUE THREAD

**Issue by xiaoshihoua** [longcw/RoIAlign.pytorch#21]
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/home/lzy/.local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

**Comment by longcw** [comment]
https://github.com/longcw/RoIAlign.pytorch/issues/20#issuecomment-446429538
