### ISSUE TITLE
    from ._crop_and_resize import lib as _lib, ffi as _ffi ModuleNotFoundError: No module named 'roi_align._ext.crop_and_resize._crop_and_resize'

### ISSUE THREAD

**Issue by KainingYing** [longcw/RoIAlign.pytorch#35]
when i test,i saw the problem.
how can i solve it?
ying@ying-TM1701:~/下载/RoIAlign.pytorch-pytorch_0.4$ ./tests
bash: ./tests: 是一个目录
(pytorch0.4.1_group) ying@ying-TM1701:~/下载/RoIAlign.pytorch-pytorch_0.4$ ./test.sh
Unexpected error: <class 'ModuleNotFoundError'>
Traceback (most recent call last):
  File "tests/test.py", line 13, in <module>
    from roi_align.crop_and_resize import CropAndResizeFunction
  File "/home/ying/.conda/envs/pytorch0.4.1_group/lib/python3.6/site-packages/roi_align-0.0.1-py3.6.egg/roi_align/crop_and_resize.py", line 7, in <module>
    from ._ext import crop_and_resize as _backend
  File "/home/ying/.conda/envs/pytorch0.4.1_group/lib/python3.6/site-packages/roi_align-0.0.1-py3.6.egg/roi_align/_ext/crop_and_resize/__init__.py", line 3, in <module>
    from ._crop_and_resize import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'roi_align._ext.crop_and_resize._crop_and_resize'
Traceback (most recent call last):
  File "tests/test2.py", line 5, in <module>
    from roi_align.roi_align import RoIAlign
  File "/home/ying/.conda/envs/pytorch0.4.1_group/lib/python3.6/site-packages/roi_align-0.0.1-py3.6.egg/roi_align/roi_align.py", line 4, in <module>
    from .crop_and_resize import CropAndResizeFunction, CropAndResize
  File "/home/ying/.conda/envs/pytorch0.4.1_group/lib/python3.6/site-packages/roi_align-0.0.1-py3.6.egg/roi_align/crop_and_resize.py", line 7, in <module>
    from ._ext import crop_and_resize as _backend
  File "/home/ying/.conda/envs/pytorch0.4.1_group/lib/python3.6/site-packages/roi_align-0.0.1-py3.6.egg/roi_align/_ext/crop_and_resize/__init__.py", line 3, in <module>
    from ._crop_and_resize import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'roi_align._ext.crop_and_resize._crop_and_resize'
Traceback (most recent call last):
  File "tests/crop_and_resize_example.py", line 5, in <module>
    from roi_align.crop_and_resize import CropAndResizeFunction
  File "/home/ying/.conda/envs/pytorch0.4.1_group/lib/python3.6/site-packages/roi_align-0.0.1-py3.6.egg/roi_align/crop_and_resize.py", line 7, in <module>
    from ._ext import crop_and_resize as _backend
  File "/home/ying/.conda/envs/pytorch0.4.1_group/lib/python3.6/site-packages/roi_align-0.0.1-py3.6.egg/roi_align/_ext/crop_and_resize/__init__.py", line 3, in <module>
    from ._crop_and_resize import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'roi_align._ext.crop_and_resize._crop_and_resize'

**Comment by Yinhance** [comment]
have u solved it？
