### ISSUE TITLE
ImportError: No module named crop_and_resize_cpu

### ISSUE THREAD

**Issue by vusdo** [longcw/RoIAlign.pytorch#45]
deep-server@server:~/Air-Clothing-MA$ python file_demo.py 
Traceback (most recent call last):
  File "file_demo.py", line 10, in <module>
    from model import EncoderClothing, DecoderClothing
  File "/home/deep-server/Air-Clothing-MA/model.py", line 6, in <module>
    from roi_align.roi_align import RoIAlign
  File "build/bdist.linux-x86_64/egg/roi_align/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/roi_align/roi_align.py", line 4, in <module>
  File "build/bdist.linux-x86_64/egg/roi_align/crop_and_resize.py", line 7, in <module>
ImportError: No module named crop_and_resize_cpu

![image](https://user-images.githubusercontent.com/1594736/102566323-a6ea5280-4122-11eb-9b47-219fc31b04d6.png)

**Comment by 297759351** [comment]
you should run setup.py first
